Id: Cryptomator.Cryptomator
Version: 1.5.6                                             
Name: Cryptomator
Publisher: Cryptomator.org
Homepage: https://cryptomator.org/
License: GNU General Public License v3.0
Description: Multi-platform transparent client-side encryption of your files in the cloud https://cryptomator.org/
Installers: 
    - Arch: x64
      Url:  https://github.com/cryptomator/cryptomator/releases/download/1.5.6/Cryptomator-1.5.6-x64.exe
      InstallerType: Inno
      Sha256: 1eaaa64f81c11fa3c9ffa0a0de68f53a1d21231733bbe243ef500daea3e88d69
